{
 "title": "Jenkins CI/CD Dashboard",
 "tags": [
  "jenkins",
  "ci-cd",
  "logs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jenkins Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_uptime_seconds", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Total Executors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_count_value", "legendFormat": "Total Executors" }
   ]
  },
  {
   "title": "Active Build Executions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_in_use_value", "legendFormat": "Executors In Use" }
   ]
  },
  {
   "title": "Jenkins Automation Server Logs (Loki Stream)",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{service=\"jenkins\"}"
    }
   ]
  }
 ]
}